version: '3'
services: 
    db:
        image: mysql
        container_name: mysql-django 
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: djangodatabasepass
        volumes:
            - ./banco01/data:/var/lib/mysql 
        restart: always
        ports:
            - "3066:3066"
        links:
            - "db"
    django:
        build: "./"
        container_name: python-django
        volumes:
            - ./qcursos:/usr/src/app
        ports:
            - "8000:8000"
        depends_on: 
            - db 
        links:
            - "db"