version: '3'
services: 
    db:
        image: mysql
        container_name: mysql-django 
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: djangodatabasepass
        volumes:
            - ./data:/var/lib/mysql 
        restart: always